### ISSUE TITLE
ShrinkWrap the GridList

### ISSUE THREAD

**Issue by Digolodollarz** [hauketoenjes/responsive_grid_list#1]
Add the option to ShrinkWrap the grid for use in a scrollview

**Comment by hauketoenjes** [comment]
I'll look into this issue in a few weeks

**Comment by hauketoenjes** [comment]
[Version 1.2.2](https://pub.dev/packages/responsive_grid_list/versions/1.2.2) of the package has been published on pub.dev with the ability to add `shrinkWrap` to `ResponsiveGridList`.
