### ISSUE TITLE
Please add a future for enable/disable scrolling

### ISSUE THREAD

**Issue by harunethm** [hauketoenjes/responsive_grid_list#10]

**Comment by hauketoenjes** [comment]
Hi, can you please provide a more clear description of the feature you are missing?

**Comment by hauketoenjes** [comment]
I just released version 1.3.0 of this package with the possibility to access the underlying `ListView` options. Maybe this has resolved your issue. Please let me know if there are any further questions.

For more information and changes, see: https://github.com/hauketoenjes/responsive_grid_list/releases/tag/v1.3.0

**Comment by harunethm** [comment]
Sorry for late response, thanks for update. Thats exactly what i want to.
