### ISSUE TITLE
Flutter 3.3. - No way to use PrimaryScrollController on Desktop/Web platforms

### ISSUE THREAD

**Issue by SaltH2OFish** [hauketoenjes/responsive_grid_list#11]
**Issue:** No way to use PrimaryScrollController on Desktop/Web platforms due to it no longer automatically attaching to vertical ScrollViews on desktop platforms with Flutter 3.3+

**Use Case:** This is necessary so an application can detect the position and retrieve additional data (infinite scroll).

**Possible Solution:** Either expose a way to set the ListView.Builder.primary parameter OR allow passing in a ScrollController. 

**Flutter 3.3 behavior change documentation**
https://docs.flutter.dev/release/breaking-changes/primary-scroll-controller-desktop

**Comment by hauketoenjes** [comment]
Thanks for the issue. I will take a look at it next week 👍🏼

**Comment by hauketoenjes** [comment]
I just released version 1.3.0 of this package with the possibility to access the underlying `ListView` options. This should resolve the issue. 

For more information and changes, see: https://github.com/hauketoenjes/responsive_grid_list/releases/tag/v1.3.0
