### ISSUE TITLE
dynamic height aka masonry/staggered

### ISSUE THREAD

**Issue by MichalNemec** [hauketoenjes/responsive_grid_list#15]
Hello, im using your library on version `responsive_grid_list: ^1.3.1` and i have trouble of making dynamic height cards within.
My expectation is 
![image](https://user-images.githubusercontent.com/5663019/219826042-164cfe4c-e6f8-4cef-b3d0-61b7095a632f.png)

my code 
```dart
ResponsiveSliverGridList(
        horizontalGridSpacing: 16,
        verticalGridSpacing: 16,
        horizontalGridMargin: 0,
        verticalGridMargin: 0,
        minItemWidth: 400,
        minItemsPerRow: 1,
        maxItemsPerRow: 6,
        rowMainAxisAlignment: MainAxisAlignment.start,
        sliverChildBuilderDelegateOptions: SliverChildBuilderDelegateOptions(),
        children: items.asMap().entries.map(
          (e) {
            final page = items[e.key];
            return Container(
                child: Text(page.text), //can be length of null or 5+ paragraphs
              );
          },
        ).toList(),
      ),
```

**Comment by hauketoenjes** [comment]
Hi, 

Unfortunately, the use case you are describing can't be provided by this package. The package only provides a responsive grid which increases or decreases the number of items in one row. It will always set the size of a row to the largest item in that row. It won't stagger the items.

But there are other packages which should fit your use case, like 
- https://pub.dev/packages/flutter_staggered_grid_view
