### ISSUE TITLE
How to use ResponsiveGridListBuilder ?

### ISSUE THREAD

**Issue by Trung15010802** [hauketoenjes/responsive_grid_list#23]
I don't see any use case to use ResponsiveGridListBuilder.
Could you make an example please?

**Comment by hauketoenjes** [comment]
Hey, 

The package internally builds Rows that contains as many items as fit with the configuration parameters. By default, it uses a `ListView.builder` to then show those rows in a list (or a `SliverChildBuilderDelegate`). The `ResponsiveGridListBuilder` can be used to replace this behavior with a custom widget to render the list of columns.

That is the use case for this.
