### ISSUE TITLE
ResponsiveGridList padding issue when scaffold with no AppBar 

### ISSUE THREAD

**Issue by davemg3** [hauketoenjes/responsive_grid_list#4]
Hello,

Flutter ListView padding issue when scaffold with no AppBar is reproduced in your package. Solution is to be able to specify 
`padding: EdgeInsets.zero,` in ResponsiveGridList.

see : https://stackoverflow.com/questions/52105557/how-to-remove-automatic-safearea-from-listview
and : https://github.com/flutter/flutter/issues/14842

So could you update : 
ResponsiveGridList and AbstractResponsiveGridList accordingly.

thank you

**Comment by hauketoenjes** [comment]
Hi, 

There were a few issues, regarding specific `ListView` Options, when using this package.

The best way of solving this is to use `ResponsiveGridListBuilder` and return a `ListView` in the builder. You can define all your options there. 

e.g.

```dart
ResponsiveGridListBuilder(
    gridItems: [...], // define your items here
    builder: (context, items) {
      return ListView(
        padding: EdgeInsets.zero,
        children: items,
      );
    }
);
```
