### ISSUE TITLE
Propuesta

### ISSUE THREAD

**Issue by EdgarCabral** [hauketoenjes/responsive_grid_list#6]
I wish you could add one more property to the component: physics... which would allow to add the component to an existing list and thus with the physics implement that it does not have sub-scroll. (PS: sorry for my English)

**Comment by hauketoenjes** [comment]
Hi, please have a look at the `ResponsiveGridListBuilder` class mentioned in the README. In the builder method you can use any Widget you want and add all the properties (like physics).
